---
title: "bird_joins"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(here)
library(janitor)
library(dplyr)

bird_observations <- read_csv(here::here("data", "52_pp52_birds_1.csv"))
sites <- read_csv(here::here("data", "52_pp52_sites_1.csv"))
surveys <- read_csv(here::here("data", "52_pp52_surveys_1.csv"))
taxalist <- read_csv(here::here("data", "52_pp52_taxalist_1.csv"))

```

```{r}
birds_subset <- bird_observations %>%
  subset(species_id %in% c("BHCO", "RWBL")) %>%
  subset(site_id %in% c("LI-W", "NU-C"))
```

```{r}
birds_left <- birds_subset%>%
  left_join(sites)%>%
              left_join(taxalist)

```
#both work. Look into it
```{r}
birds_left <- birds_subset %>%
  left_join(sites, by = "site_id") %>%
  left_join(taxalist, by = "species_id")
```

```{r}

birds_full <- full_join(birds_subset, sites, by = "site_id")

```


```{r}
birds<- bird_observations %>%
  rename(bird_obs_notes = notes)
```

```{r}
full <- birds %>%
  full_join(taxalist) %>%
  full_join(sites) %>%
  full_join(surveys)
```


```{r}
subset_full <- full %>%
  select(survey_date, common_name, park_name, bird_count)
  
```


```{r}
subset_full <- subset_full %>%
  mutate(survey_month = lubridate::month(survey_date))
```

```{r}
subset_full <- subset_full %>%
dplyr::relocate(survey_month, .after = survey_date)
```

```{r}
subset_full <- subset_full %>%
group_by(park_name, survey_month) %>%
summarise(total_number = n())
```





